Nerf beams against ridley
randovania/open-samus-returns-rando pull request #247
Opened 2024-01-08 16:02 UTC by ThanatosGit

Don't know when or if I will test it. But we have beta testers :)
(raising it for wave beam and plasma beam was working)

2024-01-08 16:35 UTC, dyceron reviewed
Do we not have worry about charge? Also what about ice? It ends up being stronger than wave and power now

2024-01-08 17:49 UTC, ThanatosGit commented
> Do we not have worry about charge?
See:
> Don't know when or if I will test it. But we have beta testers :)

All bullets should be:
Power Beam: 3 (25 * 0,12)
Ice: 10
Wave: 6 (50 *0,12)
Spazer: 25,2 (210 * 0,12)
Plasma: 36 (default of 12 * 3)

So, we make Wave to be 14 or 15?

2024-01-08 18:04 UTC, dyceron commented
> All bullets should be:
> Power Beam: 3 (25 * 0,12)
> Ice: 10
> Wave: 6 (50 *0,12)
> Spazer: 25,2 (210 * 0,12)
> Plasma: 36 (default of 12 * 3)
> 
> So, we make Wave to be 14 or 15?
> 

We could have Wave be 0.17 which is 8.5 damage or 1/3 of spazer (literally makes sense). Following that, Power could be 4.25 (0.17) or half of Wave as its normally half the strength of Wave, then have Ice use 0.33 or 3.33 damage

2024-01-09 16:03 UTC, dyceron requested changes

2024-01-09 16:03 UTC, dyceron commented on src/open_samus_returns_rando/specific_patches/static_fixes.py
> +    ridley_bmsad.components["LIFE"].raw["fields"]["fWaveBeamFactor"]["value"] = 0.12
I think we decided on 14? Change it 0.28.

2024-01-09 16:46 UTC, dyceron approved these changes

2024-01-09 16:46 UTC, merged