Add custom chozo seals
randovania/open-samus-returns-rando pull request #261
Opened 2024-01-27 06:58 UTC by dyceron

Adds new Chozo Seals to areas scenarios which do not have them. These new seals will be strictly used for DNA hints. Seals have been added to the following scenarios:

area3b - Lowest Gamma+ Arena

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/b8a7553d-c8a7-4101-97d1-f2de7ec106a8)

area5 - Gamma Arena Lower CC

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/2a8502de-722f-4403-99c8-a3c19c742782)

area6b - Top of Tower

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/6d2fdf73-169a-471d-8f04-26ef99e0bb69)
 
area10 - Middle Hallway before the big room

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/da6da03b-ec7f-43f4-81ba-d51ac68ae60e)

area10 - After the Queen (deactivated until the Queen is defeated)

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/9ef2ffd8-912e-4575-ba66-1463b09a557b)

surfaceb - Before the Teleporter

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/8f323932-bfb1-44ac-947d-c16873cff444)

Unsure how many of these I should add, or if I should add more. I think adding one more earlier on that doesn't require many items could be a good thing. Unsure about adding one in a6/a7 though.

2024-01-27 07:08 UTC, ThanatosGit requested changes

2024-01-27 07:08 UTC, ThanatosGit commented on src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py
> +    add_surfaceb_seal(editor)
Please don't matter endless copies of the same function, if all you really want to do is the same just with different parameters.

2024-01-28 18:50 UTC, ThanatosGit commented on src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py
> +    add_surfaceb_seal(editor)
The rewrite is completly missing my point here about `do [...] the same just with different parameters`.  It has swapped endless copies of a function for a new spaghetti function which checks for the scenario every second line.

You already started to use a proper data structure by extracting the coordinates but then sadly stopped.

I was thinking about something like the following. Such that if you want to modify, remove or add another seal, you don't have to touch any code besides adding a `NewChozoSeal` object to the list.

```python
import typing

class NewChozoSeal(typing.NamedTuple):
    scenario: str
    coordinates: tuple[(float, float, float)]
    ap_coordinates: tuple[(float, float, float)]
    tile_index: int
    entity_groups: list[str]
    ap_name: str = "LE_RandoDNA"
    platform_name: str = "LE_Platform_RandoDNA"

new_seals = [
    NewChozoSeal(
        "s033_area3b", [-3800.0, -16800.0, 0.0], [-3800.0, -16800.0, 0.0], 22, ["collision_camera_033", "PostGamma_004"]
    )
]

def add_chozo_seals(editor: PatcherEditor, new_seal: NewChozoSeal):
    template_ap = editor.get_scenario("s000_surface").raw.actors[16]["LE_ChozoUnlockAreaDNA"]
    template_platform = editor.get_scenario("s000_surface").raw.actors[10]["LE_Platform_ChozoUnlockAreaDNA"]
    
    CHOZO_SEAL_ICON = Container({
        "actor_name": "LE_RandoDNA",
        "clear_condition": "",
        "icon": "systemmechdna",
        "icon_priority": 4,
        "coordinates": ListContainer(new_seal.coordinates),
    })
    ...
    rest of the code
    ...
   # e.g. the whole entity group part will just look like this
    for entity_group in new_seal.entity_groups:
        scenario_file.add_actor_to_entity_groups(entity_group, new_ap, True)
        scenario_file.add_actor_to_entity_groups(entity_group, new_platform, True)

def patch_chozo_seals(editor: PatcherEditor):
    patch_dna_check(editor)
    for new_seal in new_seals:
        add_chozo_seals(editor, new_seal)
```

2024-01-28 20:48 UTC, ThanatosGit commented on src/open_samus_returns_rando/specific_patches/chozo_seal_patches.py
> +    platform_coordinates: tuple[(float, float, float)]
Oops, that was wrong on my side! We are actually just using a `list[float]` for both.

2024-01-28 20:49 UTC, ThanatosGit approved these changes
Nice. Looks much cleaner now. Only one `if-else-block` required for the surface shenanigans 👍

Just change the type where I did it wrong and go for the merge it.

2024-01-28 20:50 UTC, dyceron commented
> Nice. Looks much cleaner now. Only one `if-else-block` required for the surface shenanigans 👍
> 
> Just change the type where I did it wrong and go for the merge it.

I kinda wish I could think of these things, but that will come with time I guess. I wonder if it's worth revisiting other files like this. For later.

2024-01-28 20:52 UTC, merged