Support shuffling block types
randovania/open-samus-returns-rando pull request #414
Opened 2024-07-14 22:57 UTC by dyceron

Changes all the blocks of a certain type to another type. Note that this is a chaos option that currently will not support logic in Randovania, but the groundwork for it is there if that ever happens.

2024-07-15 05:53 UTC, ThanatosGit requested changes
More general question: How is that supposed to work with the static changes?
Should this be pre- or post the static_fixes?
Does this even make a difference? The A1 teleporter crumbles doesn't really care what block type they are.

Can you destroy a crumble block in a one tile gap within a wall or will all those pickups be unacessible then?

2024-07-15 05:53 UTC, ThanatosGit commented on src/open_samus_returns_rando/misc_patches/block_patches.py
> +                    temp_type = original_type
Please remove the `temp_type` shenanigans and just use `break` to stop the inner `for` loop.

2024-07-15 05:58 UTC, Miepee commented
> Can you destroy a crumble block in a one tile gap within a wall or will all those pickups be unacessible then?

A ~~weight~~ crumble block gets destroyed if you touch it, doesn't necessarily have to be from above. You can just jump into them, spider boost into them, probably morph into them doesn't really matter.

As example, dcr had a test seed where the power bomb blocks here were replaced with crumbles, and they just got destroyed by jumping into them from side
![grafik](https://github.com/user-attachments/assets/2aefb317-0978-4bfa-886e-5ad470ffa80b)

2024-07-15 06:22 UTC, ThanatosGit commented
They definitely don't get destroyed if touching them from below 😝.
Iirc there is even a small spot you could spider ball around the corner without them getting destroyed, that's why I asked explicitly about one tile gaps. But I assume it will be just fine and that you can destroy them from the side and have enough time to get the pickup before respawning.

2024-07-15 08:45 UTC, dyceron commented
> More general question: How is that supposed to work with the static changes? Should this be pre- or post the static_fixes? Does this even make a difference? The A1 teleporter crumbles doesn't really care what block type they are.
> 
> Can you destroy a crumble block in a one tile gap within a wall or will all those pickups be unacessible then?

I guess it should be done before or not doing the static fixes at all, but then you have the ones in game patches too.

2024-07-15 16:26 UTC, dyceron commented
I also forgot about Screw Attack blocks whoops

2024-07-16 04:37 UTC, ThanatosGit approved these changes

2024-07-16 04:37 UTC, merged